### PR TITLE
Generate index from directory tree [RFC]

### PR DESCRIPTION
**Pull request by vise890**
From a directory tree like this:
```
root
├── bar
│   └── baz.md
└── foo.md
```
the HTML index should be:
```html
<ul>
<li><a href='root'><h1>Root</h1></a></li>
<li><a href='root/foo.md'>Foo</a></li> <!-- note files before folders -->
<li><h2><a href='root/bar'>Bar</h2></a></li>
<li><a href='root/bar/baz.md'>Baz</a></li>
</ul>
```
## Contents

- [x] list files before directories
- [x] niceify names (no underscores, no extensions)
- [x] hyperlink files to correct path

### CODE REVIEW

**Comment by vise890** [comment]
@maxmcd this is ready for you to review

Basically:

The HTML index is generated in two conceptual steps:

1. make an `indexTree` out of a directory structure. This `indexTree` is an intermediate representation of  the index. you can find the logic for this in `index_tree.go` and linked files;
2. generate an HTML index from the `indexTree` representation. The bulk of the work is done in the `renderIndex` function in `page.go` and `section.go`

**Comment by maxmcd** [comment]
Looks good to me. Ready to merge

**Comment by vise890** [comment]
Should we squash the commits?

**Comment by maxmcd** [comment]
Nah, love me some detailed commits

**Pull request merged**
